config/routes.rb
Rails.application.routes.draw do
  root 'pessoas#index'
  devise_for :users
  resources :pessoas

end

app/models/imagem.rb
class Imagem < ActiveRecord::Base
  belongs_to :pessoa
  attachment :file
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
	include PgSearch
	pg_search_scope :search_nome, :against => [:nome_completo, :alcunha, :tatuagem_descricao], :using => {
																										:tsearch => {:prefix => true, :any_word => true }, 
																										:dmetaphone => {},
																										:trigram => {}
																											}
																						

	has_many :imagems, dependent: :destroy
	accepts_attachments_for :imagems, attachment: :file, append: true

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /pessoas
  # GET /pessoas.json
  def index
    if params[:search] 
      #@soma =  Pessoa.search_errado(params[:search])
      @pessoas = Pessoa.search_nome(params[:search]).paginate(:page => params[:page], :per_page => 6)
    else 
      @pessoas = Pessoa.paginate(:page => params[:page], :per_page => 6)
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Criado com Sucesso.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Dados Atualizados com Sucesso.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Dados deletados com Sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome_completo, :alcunha, :idade, :nome_mae,  :data_nascimento,
        :nome_pai,  :endereco, :cidade, :zona, :estado, :pais, :observacao_1, :tatuagem_descricao, :identidade, :cpf, :pratica_criminal,  :mandado_prisao, :condenacao, :sexo, 
        :altura, :cor_do_olho, :cor_cabelo, :com_fisica, :marca_sinal, :comparsa, imagems_files: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    </head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Foto">
    <meta name="Mardem Lincow" content="foto">
    <title>Agnesco</title>
</head>
<body>
	<header>
	    <div class="container">
	        <div class="row">
	        	<!-- Logo -->
	            <div class="col-lg-4 col-md-3 hidden-sm hidden-xs">
	            	<div class="well logo">
	            		<a href="index.html">
	            			Agnesco <span>Alpha</span>
	            		</a>
	            		<div>Sistema de Fotografias.</div>   
	            	</div>
	            </div>
	            <!-- End Logo -->

				<!-- Search Form -->
	           
                <%= render "pessoas/busca" %>
	            <!-- End Search Form -->

	            <!--  acoes -->
	             <%= render "pessoas/acoes" %>
	            <!-- end acoes  List -->
	        </div>
	    </div>
    </header>
	<!-- Navigation -->
     <%= render "pessoas/menu" %>
    <!-- End Navigation -->
    <div class="container main-container">
        <div class="row">

			<!-- Selection, visible only on large desktop -->
            <div class="col-lg-3 visible-lg">
                <div class="row text-center">
                    
                </div>
            </div>
            <!-- End Product Selection -->
        </div>

        <div class="row">
        	<div class="col-lg-3 col-md-3 col-sm-12">

        	</div>

        	<div class="clearfix visible-sm"></div>

			
        	
        	<div class="clearfix visible-sm"></div>
				<%= yield %>
        </div>

	</div>
	<!-- rodape -->
	 <%= render "pessoas/rodape" %>
	<!-- fim rodape -->
	
    <a href="#top" class="back-top text-center" onclick="$('body,html').animate({scrollTop:0},500); return false">
    	<i class="fa fa-angle-double-up"></i>
    </a>

</body>
</html>

app/views/pessoas/_acoes.html.erb
<% if user_signed_in? %>
<div class="col-lg-3 col-md-4 col-sm-5">
	<div class="well">
		<div class="btn-group btn-group-cart">
			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
				<span class="pull-left"><i class="fa fa-level-down"></i></span>
				<span class="pull-left">_ Ações </span>
				<span class="pull-right"><i class="fa fa-sign-out"></i></span>
			</button>
			<ul class="dropdown-menu cart-content" role="menu">
				<li>
					<%= link_to "Sair", destroy_user_session_path, :method => :delete %>
				</li>
				<li>
					<a href="detail.html">
						<b>Ação</b>
					</a>
				</li>
			</ul>
		</div>
         <center><div><%= current_user.email %></div></center>
	</div>
</div>

<% end %>

app/views/pessoas/_busca.html.erb
<% if user_signed_in? %>
<div class="col-lg-5 col-md-5 col-sm-7 col-xs-12">
	<div class="well">
		 <%= form_tag pessoas_path, :method => 'get', class: 'input-group'  do %>
		    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Buscar...' %>
		    <span class="input-group-btn">
		      <%= submit_tag "Buscar", class: "btn btn-default" %>
		    </span>
  		<% end %>
	</div>
</div>
<% end %>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-12 col-sm-12 hero-feature">
    <div class="table-responsive">
      <table class="table table-bordered tbl-checkout">
          <tbody>
              <tr>
                <td>Nome Completo</td>
                  <td>
                      <%= f.text_field :nome_completo , :class=> "form-control" %>  
              </td>
              <td>Alcunha</td>
              <td>
                   <%= f.text_field :alcunha , :class=> "form-control" %>
              </td>
          </tr>
          <tr>
              <td>Pai</td>
              <td>
                  <%= f.text_field :nome_pai , :class=> "form-control" %>
              </td>
              <td>Mãe</td>
              <td>
                  <%= f.text_field :nome_mae , :class=> "form-control" %>
              </td>
          </tr>
          <tr>
          <td>Data de Nacimento</td>
            <td>
              <%= f.date_field :data_nascimento ,  :class=> "form-control" %>  
            </td>
            </tr>
          <tr>
              <td>Último Endereço</td>
              <td colspan="3">
                  <%= f.text_area :endereco ,  :class=> "form-control" %>
              </td>
          </tr>

           <tr>
              <td>Cidade</td>
              <td>
                  <%= f.text_field :cidade ,  :class=> "form-control" %>
              </td>
              <td>Zona</td>
              <td>
                  <%= f.text_field :zona ,  :class=> "form-control" %>
              </td>
          </tr>

          <tr>
            <td>Estado</td>
            <td>
              <%= f.text_field :estado ,  :class=> "form-control" %>
            </td> 
            <td class="tujuan">País</td>
              <td>
                <%= f.text_field :pais ,  :class=> "form-control" %>
              </td>  
          <tr>
            <td>Observação:</td>
              <td colspan="3">
                <%= f.text_area :observacao_1 ,  :class=> "form-control" %>
              </td>
          </tr>

          <tr>
              <td>Upload de Fotos:</td>
              <td colspan="3">
                <%= f.attachment_field  :imagems_files , multiple: true, presigned: true, diret: :true %>
              </td>

              <tr>
            <td>Descrição Tatuagens:</td>
              <td colspan="3">
                <%= f.text_area :tatuagem_descricao ,  :class=> "form-control" %>
              </td>

          </tr>
          </tr>
      </tbody>
    </table>
</div>


<div class="table-responsive">
      <table class="table table-bordered tbl-checkout">
          <tbody>
              <tr>
                <td>Identidade</td>
                  <td>
                      <%= f.text_field :identidade , :class=> "form-control" %>  
              </td>
              <td>CPF</td>
              <td>
                   <%= f.text_field :cpf , :class=> "form-control" %>
              </td>
          </tr>
          <tr>
              <td>Pratica Criminal</td>
              <td>
                  <%= f.text_area :pratica_criminal , :class=> "form-control" %>
              </td>
              <td>Mandado de Prisão nº </td>
              <td>
                  <%= f.text_field :mandado_prisao , :class=> "form-control" %>
              </td>
          </tr>
          <tr>
          <td>Condenação</td>
            <td>
              <%= f.text_field :condenacao ,  :class=> "form-control" %>  
            </td>
          </tr>
          
           <tr>
            <td>Sexo</td>
            <td>
              <%= f.text_field :sexo ,  :class=> "form-control" %>  
            </td>
          </tr>

           <tr>
              <td>Altura</td>
              <td>
                  <%= f.text_field :altura ,  :class=> "form-control" %>
              </td>
              <td>Cor dos olhos</td>
              <td>
                  <%= f.text_field :cor_do_olho ,  :class=> "form-control" %>
              </td>
          </tr>

          <tr>
            <td>Cor do cabelo</td>
            <td>
              <%= f.text_field :cor_cabelo ,  :class=> "form-control" %>
            </td> 
            <td class="tujuan">Compleição Física</td>
              <td>
                <%= f.text_field :comp_fisica ,  :class=> "form-control" %>
              </td>  
          <tr>
            <td>Marcas e Sinais:</td>
              <td colspan="3">
                <%= f.text_area :marca_sinal ,  :class=> "form-control" %>
              </td>
          </tr>

          <tr>
            <td>Comparsas:</td>
              <td colspan="3">
                <%= f.text_area :comparsa ,  :class=> "form-control" %>
              </td>
          </tr>  

      </tbody>
    </table>
</div>


            
          <div class="btn-group btns-cart">
              <%= f.submit "Continue", :class=> "btn btn-primary" %> 
          </div>
          <p> <%= link_to 'Voltar', pessoas_path %> </p>
</div>
  
<% end %>

app/views/pessoas/_menu.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- text logo on mobile view -->
                <a class="navbar-brand visible-xs" href="index.html">Mimity Online Shop</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li> <%= link_to 'HOME', pessoas_path, :class=> "active" %></li>
                    <li> <%= link_to 'INSERIR', new_pessoa_path %></li>
                    <li><a href="cart.html">Busca Avançada</a></li>
                    <li><a href="checkout.html">Mais Procurados</a></li>
                    <li class="nav-dropdown">
                    	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Pages <span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="blog-detail.html">Blog Detail</a></li>
                            <li><a href="compare.html">Compare</a></li>
                            <li><a href="contact.html">Contact Us</a></li>
                            <li><a href="login.html">Login</a></li>
                            <li><a href="detail.html">Product Detail</a></li>
                            <li><a href="register.html">Register</a></li>
                            <li><a href="typography.html">Typography</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
<% end %>    

app/views/pessoas/_paginador.html.erb
<div class="text-center">
	<%= will_paginate @posts, :page_links => false %>
</div> 

app/views/pessoas/_rodape.html.erb
<% if user_signed_in? %>
<footer>
    	<div class="container">
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Information</h4>
        			<ul>
        				<li><a href="about.html">About Us</a></li>
        				<li><a href="typography.html">Policy Privacy</a></li>
        				<li><a href="typography.html">Terms and Conditions</a></li>
        				<li><a href="typography.html">Shipping Methods</a></li>
        			</ul>
        		</div>
        	</div>
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Categories</h4>
        			<ul>
        				<li><a href="catalogue.html">Cras justo odio</a></li>
        				<li><a href="catalogue.html">Dapibus ac facilisis in</a></li>
        				<li><a href="catalogue.html">Morbi leo risus</a></li>
        				<li><a href="catalogue.html">Porta ac consectetur ac</a></li>
        			</ul>
        		</div>
        	</div>
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Customer Service</h4>
        			<ul>
        				<li><a href="contact.html">Contact Us</a></li>
        				<li><a href="#">YM: cs_</a></li>
        				<li><a href="#">Phone: +6281234567891</a></li>
        				<li><a href="#">Email: cs.domain@domain.tld</a></li>
        			</ul>
        		</div>
        	</div>
        	<div class="col-lg-3 col-md-3 col-sm-6">
        		<div class="column">
        			<h4>Follow Us</h4>
        			<ul class="social">
        				<li><a href="#">Google Plus</a></li>
        				<li><a href="#">Facebook</a></li>
        				<li><a href="#">Twitter</a></li>
        				<li><a href="#">RSS Feed</a></li>
        			</ul>
        		</div>
        	</div>
        </div>
        <div class="navbar-inverse text-center copyright">
        	Copyright &copy; 2015 Mimity All right reserved
        </div>
    </footer>
<% end %>

app/views/pessoas/edit.html.erb
<div class="alert alert-info" role="alert">
  <h4>Editar Dados</h4>
</div>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<div class="col-lg-9 col-md-9 col-sm-12">
  <div class="col-lg-12 col-sm-12">
    <span class="title"> Fotos </span>
    <% if notice %>
        <div class="alert alert-info" role="alert">
          <h4> <p id="notice"><%= notice %></p> <h4>
        </div>
    <% end %>    
      
  </div>
    <%  @pessoas.each do |pessoa| %>
        <div class="col-lg-4 col-sm-4 hero-feature text-center">
          <div class="thumbnail">
              <a href="detail.html" class="link-p">
                <%= attachment_image_tag(pessoa.imagems.first, :file, :fill, 580, 640, format: "jpg") %>

              </a>
            <div class="caption prod-caption">
              <h4> <%= link_to pessoa.nome_completo , pessoa %>  </a></h4>
              <h4> <%= link_to  pessoa.alcunha , pessoa %>  </a></h4>
                  <p> <%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Deseja Continuas?' } %></p>
            </div>
          </div>
      </div>        
   <% end %>               
</div>
<%= render "paginador" %>







 

app/views/pessoas/new.html.erb
<div class="alert alert-success" role="alert">
  <h4>Inserir novo Documento</h4>
</div>
<%= render 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), :class => "btn btn-sm btn-primary pull-right" %><br />
<% end -%>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), :class => "btn btn-success btn-sm pull-right"%><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), :class => "btn btn-warning btn-sm" %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>